name: "Linting"
description: ""
inputs:
  python-version:
    required: true
    description: "The python-version used to define the python"
  current_package:
    required: true
    description: "The package to lint"
runs:
  using: "composite"
  steps:
    - name: Cancel previous running workflows
      uses: fkirc/skip-duplicate-actions@master
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      shell: bash
      working-directory: ${{ inputs.current_package }}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --config=../../.flake8 --count --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --config=../../.flake8 --count --exit-zero --statistics
