name: "Linting"
description: ""
inputs:
  python-version:
    required: true
    description: "The python-version used to define the python"
  current_package:
    required: true
    description: "The package to lint"
runs:
  using: "composite"
  steps:
    - name: Cancel previous running workflows
      uses: fkirc/skip-duplicate-actions@master
    - uses: actions/checkout@v3
    - name: Install poetry
      shell: bash
      working-directory: ${{ inputs.current_package }}
      run: pipx install poetry
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
    - name: Install package dependencies
      shell: bash
      working-directory: ${{ inputs.current_package }}
      run: poetry install --only linter
    - name: Lint with flake8
      shell: bash
      working-directory: ${{ inputs.current_package }}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --config=../../.flake8 --count --show-source --statistics
        # exit-zero treats all errors as warnings.
        poetry run flake8 . --config=../../.flake8 --count --exit-zero --statistics
