# Generated by Django 4.2.7 on 2023-12-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_flaskaddress_flaskcustomer_flaskorder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedCart",
            fields=[
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app.cart",
                    ),
                ),
                ("color", models.CharField(max_length=20)),
            ],
        ),
    ]
