# Generated by Django 4.2.7 on 2023-12-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_extendedcart"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="extendedcart",
            name="discount",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.discountcart",
            ),
        ),
    ]
