# Generated by Django 4.2.11 on 2024-07-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("app", "0005_customer_blocked_customer_alter_customer_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("record_pk", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="address",
            name="customers",
        ),
        migrations.AddField(
            model_name="address",
            name="addressable_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="addressable_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="blocked_customer",
            field=models.ManyToManyField(
                blank=True, related_name="block_by_users", to="app.customer"
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagged_item_id", models.IntegerField()),
                ("tag", models.CharField(max_length=255)),
                (
                    "tagged_item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("tagged_item_type", "tagged_item_id")},
            },
        ),
    ]
