# Generated by Django 4.2.11 on 2024-06-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("app", "0005_customer_blocked_customer_alter_customer_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="addressable_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="addressable_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="blocked_customer",
            field=models.ManyToManyField(
                blank=True, related_name="block_by_users", to="app.customer"
            ),
        ),
    ]
