[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "forestadmin-agent-django"
version = "1.3.0-beta.2"
description = ""
authors = [ "Julien Barreau <julien.barreau@forestadmin.com>",]
readme = "README.md"
[[tool.poetry.packages]]
include = "forestadmin"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
typing-extensions = "~=4.2"
tzdata = "~=2022.6"
forestadmin-agent-toolkit = "1.3.0-beta.2"
forestadmin-datasource-django = "1.3.0-beta.2"
django = ">=3.2,<5.0"
django-cors-headers = ">=3.8"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "test_project_agent.settings"
pythonpath = "tests/test_project_agent"

[tool.poetry.dependencies."backports.zoneinfo"]
version = "~=0.2.1"
python = "<3.9"
extras = [ "tzdata",]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.linter]
optional = true

[tool.poetry.group.formatter]
optional = true

[tool.poetry.group.sorter]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "~=7.1"
pytest-asyncio = "~=0.18"
coverage = "~=6.5"
freezegun = "~=1.2.0"
pytest-cov = "^4.0.0"
pytest-django = ">=4.0.0"

[tool.poetry.group.linter.dependencies]
[[tool.poetry.group.linter.dependencies.flake8]]
version = "~=5.0"
python = "<3.8.1"

[[tool.poetry.group.linter.dependencies.flake8]]
version = "~=6.0"
python = ">=3.8.1"

[tool.poetry.group.formatter.dependencies]
black = "~=22.10"

[tool.poetry.group.sorter.dependencies]
isort = "~=3.6"

[tool.poetry.group.test.dependencies.forestadmin-datasource-django]
path = "../datasource_django"
develop = true

[tool.poetry.group.test.dependencies.forestadmin-datasource-toolkit]
path = "../datasource_toolkit"
develop = true

[tool.poetry.group.test.dependencies.forestadmin-agent-toolkit]
path = "../agent_toolkit"
develop = true
