name: "Releasing"
description: ""
inputs:
  packages:
    required: true
    description: "The package to release"
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # - name: build versions
    #   id: build_versions
    #   shell: bash
    #   run: |
    #     echo $(newArray=( $(echo ${{ inputs.packages }} | sed -e 's/\[//g' -e 's/\]//g' -e 's/\,/ /g' -e 's/"//g') ); res=""; for value in "${newArray[@]}"; do res+="../.${value}pyproject.toml:tool.poetry.version,"; done; res=${res: : -1}; echo "VERSIONS=$res") >> $GITHUB_OUTPUT
    # - name: Semantic Release
    #   shell: bash
    #   working-directory:  ${{ inputs.packages }}
    #   run: |
    #     pip install python-semantic-release<=8
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     semantic-release publish --prerelease -D changelog_file="../../CHANGELOG.md" -D version_toml=${{ steps.build_versions.outputs.VERSIONS }}

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        semantic_version: 17.3.0
      env:
        # PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
        GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
        GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
        GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
