name: "Releasing"
description: ""
inputs:
  packages:
    required: true
    description: "The package to release"
  GH_TOKEN:
    required: true
  GIT_AUTHOR_EMAIL:
    required: true
  GIT_AUTHOR_NAME:
    required: true
  GIT_COMMITTER_EMAIL:
    required: true
  GIT_COMMITTER_NAME:
    required: true
  SLACK_WEBHOOK:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false # GITHUB_TOKEN must not be set for the semantic release
    - uses: actions/setup-node@v2
      with:
        node-version: 14.17.6
    # - uses: actions/cache@v2
    #   with:
    #     path: '**/node_modules'
    #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: install dependencies
      shell: bash
      run: yarn install --non-interactive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python-toml
      shell: bash
      run: python -m pip install toml
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        semantic_version: 17.3.0
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        GIT_AUTHOR_EMAIL: ${{ inputs.GIT_AUTHOR_EMAIL }}
        GIT_AUTHOR_NAME: ${{ inputs.GIT_AUTHOR_NAME }}
        GIT_COMMITTER_EMAIL: ${{ inputs.GIT_COMMITTER_EMAIL }}
        GIT_COMMITTER_NAME: ${{ inputs.GIT_COMMITTER_NAME }}
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
