# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forestadmin/rpc_common/proto/collection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'forestadmin/rpc_common/proto/collection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from forestadmin.rpc_common.proto import forest_pb2 as forestadmin_dot_rpc__common_dot_proto_dot_forest__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-forestadmin/rpc_common/proto/collection.proto\x12\x0e\x64\x61tasource_rpc\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a)forestadmin/rpc_common/proto/forest.proto\"{\n\x16\x43ollectionChartRequest\x12&\n\x06\x63\x61ller\x18\x01 \x01(\x0b\x32\x16.datasource_rpc.Caller\x12\x11\n\tChartName\x18\x02 \x01(\t\x12&\n\x08RecordId\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"d\n\rCreateRequest\x12&\n\x06\x43\x61ller\x18\x01 \x01(\x0b\x32\x16.datasource_rpc.Caller\x12+\n\nRecordData\x18\x02 \x03(\x0b\x32\x17.google.protobuf.Struct2\x98\x01\n\nCollection\x12K\n\x0bRenderChart\x12&.datasource_rpc.CollectionChartRequest\x1a\x14.google.protobuf.Any\x12=\n\x06\x43reate\x12\x1d.datasource_rpc.CreateRequest\x1a\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forestadmin.rpc_common.proto.collection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLECTIONCHARTREQUEST']._serialized_start=165
  _globals['_COLLECTIONCHARTREQUEST']._serialized_end=288
  _globals['_CREATEREQUEST']._serialized_start=290
  _globals['_CREATEREQUEST']._serialized_end=390
  _globals['_COLLECTION']._serialized_start=393
  _globals['_COLLECTION']._serialized_end=545
# @@protoc_insertion_point(module_scope)
