# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from forestadmin.rpc_common.proto import collection_pb2 as forestadmin_dot_rpc__common_dot_proto_dot_collection__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in forestadmin/rpc_common/proto/collection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenderChart = channel.unary_unary(
                '/datasource_rpc.Collection/RenderChart',
                request_serializer=forestadmin_dot_rpc__common_dot_proto_dot_collection__pb2.CollectionChartRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/datasource_rpc.Collection/Create',
                request_serializer=forestadmin_dot_rpc__common_dot_proto_dot_collection__pb2.CreateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
                _registered_method=True)


class CollectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RenderChart(self, request, context):
        """Define your RPC methods here
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """crud
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenderChart': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderChart,
                    request_deserializer=forestadmin_dot_rpc__common_dot_proto_dot_collection__pb2.CollectionChartRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=forestadmin_dot_rpc__common_dot_proto_dot_collection__pb2.CreateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datasource_rpc.Collection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datasource_rpc.Collection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Collection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RenderChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datasource_rpc.Collection/RenderChart',
            forestadmin_dot_rpc__common_dot_proto_dot_collection__pb2.CollectionChartRequest.SerializeToString,
            google_dot_protobuf_dot_any__pb2.Any.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datasource_rpc.Collection/Create',
            forestadmin_dot_rpc__common_dot_proto_dot_collection__pb2.CreateRequest.SerializeToString,
            google_dot_protobuf_dot_any__pb2.Any.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
