# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forestadmin/rpc_common/proto/datasource.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'forestadmin/rpc_common/proto/datasource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from forestadmin.rpc_common.proto import forest_pb2 as forestadmin_dot_rpc__common_dot_proto_dot_forest__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-forestadmin/rpc_common/proto/datasource.proto\x12\x0e\x64\x61tasource_rpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a)forestadmin/rpc_common/proto/forest.proto\"y\n\x0eSchemaResponse\x12\x30\n\x06Schema\x18\x01 \x01(\x0b\x32 .datasource_rpc.DataSourceSchema\x12\x35\n\x0b\x43ollections\x18\x02 \x03(\x0b\x32 .datasource_rpc.CollectionSchema\"S\n\x16\x44\x61tasourceChartRequest\x12&\n\x06\x63\x61ller\x18\x01 \x01(\x0b\x32\x16.datasource_rpc.Caller\x12\x11\n\tChartName\x18\x02 \x01(\t\"\xdc\x01\n\x12NativeQueryRequest\x12&\n\x06\x43\x61ller\x18\x01 \x01(\x0b\x32\x16.datasource_rpc.Caller\x12\r\n\x05Query\x18\x02 \x01(\t\x12\x46\n\nParameters\x18\x03 \x03(\x0b\x32\x32.datasource_rpc.NativeQueryRequest.ParametersEntry\x1aG\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x32\xeb\x01\n\nDataSource\x12@\n\x06Schema\x12\x16.google.protobuf.Empty\x1a\x1e.datasource_rpc.SchemaResponse\x12K\n\x0bRenderChart\x12&.datasource_rpc.DatasourceChartRequest\x1a\x14.google.protobuf.Any\x12N\n\x12\x45xecuteNativeQuery\x12\".datasource_rpc.NativeQueryRequest\x1a\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forestadmin.rpc_common.proto.datasource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NATIVEQUERYREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_NATIVEQUERYREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_SCHEMARESPONSE']._serialized_start=164
  _globals['_SCHEMARESPONSE']._serialized_end=285
  _globals['_DATASOURCECHARTREQUEST']._serialized_start=287
  _globals['_DATASOURCECHARTREQUEST']._serialized_end=370
  _globals['_NATIVEQUERYREQUEST']._serialized_start=373
  _globals['_NATIVEQUERYREQUEST']._serialized_end=593
  _globals['_NATIVEQUERYREQUEST_PARAMETERSENTRY']._serialized_start=522
  _globals['_NATIVEQUERYREQUEST_PARAMETERSENTRY']._serialized_end=593
  _globals['_DATASOURCE']._serialized_start=596
  _globals['_DATASOURCE']._serialized_end=831
# @@protoc_insertion_point(module_scope)
