# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forestadmin/rpc_common/proto/forest.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'forestadmin/rpc_common/proto/forest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)forestadmin/rpc_common/proto/forest.proto\x12\x0e\x64\x61tasource_rpc\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf4\x01\n\x06\x43\x61ller\x12\x12\n\nRendererId\x18\x01 \x01(\x05\x12\x0e\n\x06UserId\x18\x02 \x01(\x05\x12.\n\x04Tags\x18\x03 \x03(\x0b\x32 .datasource_rpc.Caller.TagsEntry\x12\r\n\x05\x45mail\x18\x04 \x01(\t\x12\x11\n\tFirstName\x18\x05 \x01(\t\x12\x10\n\x08LastName\x18\x06 \x01(\t\x12\x0c\n\x04Team\x18\x07 \x01(\t\x12\x10\n\x08Timezone\x18\x08 \x01(\t\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x15\n\x07Request\x12\n\n\x02Ip\x18\x01 \x01(\t\"r\n\x10\x44\x61taSourceSchema\x12\x0e\n\x06\x43harts\x18\x01 \x03(\t\x12\x17\n\x0f\x43onnectionNames\x18\x02 \x03(\t\x12\x35\n\x0b\x43ollections\x18\x03 \x03(\x0b\x32 .datasource_rpc.CollectionSchema\"\xf8\x02\n\x10\x43ollectionSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12>\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32-.datasource_rpc.CollectionSchema.ActionsEntry\x12<\n\x06\x66ields\x18\x03 \x03(\x0b\x32,.datasource_rpc.CollectionSchema.FieldsEntry\x12\x0e\n\x06\x63harts\x18\x04 \x03(\t\x12\x12\n\nsearchable\x18\x05 \x01(\x08\x12\x11\n\tcountable\x18\x06 \x01(\x08\x12\x10\n\x08segments\x18\x07 \x03(\t\x1aG\n\x0c\x41\x63tionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x1a\x46\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forestadmin.rpc_common.proto.forest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLER_TAGSENTRY']._loaded_options = None
  _globals['_CALLER_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_COLLECTIONSCHEMA_ACTIONSENTRY']._loaded_options = None
  _globals['_COLLECTIONSCHEMA_ACTIONSENTRY']._serialized_options = b'8\001'
  _globals['_COLLECTIONSCHEMA_FIELDSENTRY']._loaded_options = None
  _globals['_COLLECTIONSCHEMA_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_CALLER']._serialized_start=119
  _globals['_CALLER']._serialized_end=363
  _globals['_CALLER_TAGSENTRY']._serialized_start=297
  _globals['_CALLER_TAGSENTRY']._serialized_end=340
  _globals['_CALLER_REQUEST']._serialized_start=342
  _globals['_CALLER_REQUEST']._serialized_end=363
  _globals['_DATASOURCESCHEMA']._serialized_start=365
  _globals['_DATASOURCESCHEMA']._serialized_end=479
  _globals['_COLLECTIONSCHEMA']._serialized_start=482
  _globals['_COLLECTIONSCHEMA']._serialized_end=858
  _globals['_COLLECTIONSCHEMA_ACTIONSENTRY']._serialized_start=715
  _globals['_COLLECTIONSCHEMA_ACTIONSENTRY']._serialized_end=786
  _globals['_COLLECTIONSCHEMA_FIELDSENTRY']._serialized_start=788
  _globals['_COLLECTIONSCHEMA_FIELDSENTRY']._serialized_end=858
# @@protoc_insertion_point(module_scope)
