name: Changes
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          ./src/datasource_toolkit/:
            - 'src/datasource_toolkit/**'
          ./src/datasource_sqlalchemy:
            - 'src/datasource_sqlalchemy/**'
          ./src/agent_toolkit:
            - 'src/agent_toolkit/**'
          ./src/flask_agent:
            - 'src/flask_agent/**'
