name: Changes
runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          ./src/datasource_toolkit/:
            - 'src/datasource_toolkit/**'
          ./src/datasource_sqlalchemy:
            - 'src/datasource_sqlalchemy/**'
          ./src/datasource_django:
            - 'src/datasource_django/**'
          ./src/agent_toolkit:
            - 'src/agent_toolkit/**'
          ./src/flask_agent:
            - 'src/flask_agent/**'
          ./src/django_agent:
            - 'src/django_agent/**'
          django_agent:
            - 'src/django_agent/**'

    - run:   echo "$OUTPUTS"
      shell: bash
      env:
        OUTPUTS: ${{ toJSON(step.changes.outputs) }}
