name: Changes
outputs:
  packages:
    description: changes on all
    value: ${{ toJSON(steps.changes.outputs) }}
runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          datasource_toolkit:
            - 'src/datasource_toolkit/**'
          datasource_sqlalchemy:
            - 'src/datasource_sqlalchemy/**'
          datasource_django:
            - 'src/datasource_django/**'
          agent_toolkit:
            - 'src/agent_toolkit/**'
          flask_agent:
            - 'src/flask_agent/**'
          django_agent:
            - 'src/django_agent/**'
