name: Changes
outputs:
  packages:
    description: changes on all
    value: ${{ toJSON(steps.changes.outputs) }}
  # django_agent:
  #   description: changes on django_agent
  #   value: ${{ steps.changes.outputs.django_agent }}
  # flask_agent:
  #   description: changes on flask_agent
  #   value: ${{ steps.changes.outputs.flask_agent }}
  # agent_toolkit:
  #   description: changes on agent_toolkit
  #   value: ${{ steps.changes.outputs.agent_toolkit }}
  # datasource_django:
  #   description: changes on datasource_django
  #   value: ${{ steps.changes.outputs.datasource_django }}
  # datasource_sqlalchemy:
  #   description: changes on datasource_sqlalchemy
  #   value: ${{ steps.changes.outputs.datasource_sqlalchemy }}
  # datasource_toolkit:
  #   description: changes on datasource_toolkit
  #   value: ${{ steps.changes.outputs.datasource_toolkit }}
runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          datasource_toolkit:
            - 'src/datasource_toolkit/**'
          datasource_sqlalchemy:
            - 'src/datasource_sqlalchemy/**'
          datasource_django:
            - 'src/datasource_django/**'
          agent_toolkit:
            - 'src/agent_toolkit/**'
          flask_agent:
            - 'src/flask_agent/**'
          django_agent:
            - 'src/django_agent/**'
