name: Run isort
inputs:
  current_package:
    required: true
    description: "The package to isort"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: isort/isort-action@master
      with:
          sortPaths: ${{ inputs.current_package }}
          requirementsFiles: "requirements.txt ../../requirements.txt"
          configurations: "--settings-file=../../.isort.cfg"