name: Run isort
inputs:
  python-version:
    required: true
    description: "The python-version used to define the python"
  current_package:
    required: true
    description: "The package to isort"
runs:
  using: "composite"
  steps:
    - name: Cancel previous running workflows
      uses: fkirc/skip-duplicate-actions@master
    - name: Install poetry
      shell: bash
      working-directory: ${{ inputs.current_package }}
      run: pipx install poetry
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
    - name: Install package dependencies
      shell: bash
      working-directory: ${{ inputs.current_package }}
      run: poetry install --only sorter
    - uses: isort/isort-action@master
      with:
          sortPaths: ${{ inputs.current_package }}
          requirementsFiles: "requirements.txt ../../requirements.txt"
          configuration: "--settings-file=./.isort.cfg"