name: ci workflow
on:
  push:
    branches:
      - beta
  pull_request:
jobs:
  GenericPackage:
    uses: ./.github/workflows/generic.yml
    with:
      packages: '["./src/datasource_toolkit/", "./src/datasource_sqlalchemy/", "./src/agent_toolkit/", "./src/flask_agent/"]'
    secrets:
      CC_TEST_REPORTER_ID: 'fake'
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}