name: ci workflow
on:
  push:
    branches:
      - beta
  pull_request:
jobs:
  GenericPackage:
    uses: ./.github/workflows/generic.yml
    with:
      packages: '["./src/datasource_toolkit/", "./src/datasource_sqlalchemy/", "./src/agent_toolkit/", "./src/flask_agent/"]'
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
      GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
      GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
      GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
