name: datasource-tookit workflow
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  GenericPackage:
    uses: ./.github/workflows/generic.yml
    with:
      current-package: './src/datasource_toolkit/'
    secrets:
      CC_TEST_REPORTER_ID: 'fake'